package com.lyc.easyreader.api.book;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import java.util.Map;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig bookFileDaoConfig;
    private final DaoConfig bookChapterDaoConfig;

    private final BookFileDao bookFileDao;
    private final BookChapterDao bookChapterDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        bookFileDaoConfig = daoConfigMap.get(BookFileDao.class).clone();
        bookFileDaoConfig.initIdentityScope(type);

        bookChapterDaoConfig = daoConfigMap.get(BookChapterDao.class).clone();
        bookChapterDaoConfig.initIdentityScope(type);

        bookFileDao = new BookFileDao(bookFileDaoConfig, this);
        bookChapterDao = new BookChapterDao(bookChapterDaoConfig, this);

        registerDao(BookFile.class, bookFileDao);
        registerDao(BookChapter.class, bookChapterDao);
    }

    public void clear() {
        bookFileDaoConfig.clearIdentityScope();
        bookChapterDaoConfig.clearIdentityScope();
    }

    public BookFileDao getBookFileDao() {
        return bookFileDao;
    }

    public BookChapterDao getBookChapterDao() {
        return bookChapterDao;
    }

}
