package com.lyc.easyreader.api.book;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.lyc.easyreader.api.book.BookChapter;
import com.lyc.easyreader.api.book.BookFile;

import com.lyc.easyreader.api.book.BookChapterDao;
import com.lyc.easyreader.api.book.BookFileDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig bookChapterDaoConfig;
    private final DaoConfig bookFileDaoConfig;

    private final BookChapterDao bookChapterDao;
    private final BookFileDao bookFileDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        bookChapterDaoConfig = daoConfigMap.get(BookChapterDao.class).clone();
        bookChapterDaoConfig.initIdentityScope(type);

        bookFileDaoConfig = daoConfigMap.get(BookFileDao.class).clone();
        bookFileDaoConfig.initIdentityScope(type);

        bookChapterDao = new BookChapterDao(bookChapterDaoConfig, this);
        bookFileDao = new BookFileDao(bookFileDaoConfig, this);

        registerDao(BookChapter.class, bookChapterDao);
        registerDao(BookFile.class, bookFileDao);
    }
    
    public void clear() {
        bookChapterDaoConfig.clearIdentityScope();
        bookFileDaoConfig.clearIdentityScope();
    }

    public BookChapterDao getBookChapterDao() {
        return bookChapterDao;
    }

    public BookFileDao getBookFileDao() {
        return bookFileDao;
    }

}
